 version: 2.1
 orbs:
   newman: postman/newman@0.0.2
 jobs:
   postman:
     executor: newman/postman-newman-docker
     docker:
       - image: circleci/node:lts
#       - image: circleci/mongo:latest
#     environment:
#       - MONGO_URL: "mongodb://localhost:27017/herodb"
     steps:
       - checkout
       - run: npm install
       - run:
           command: npm run express-server
           background: true
       - run:
           command: echo 'export PATH=/usr/local/bin:$PATH newman -v' >> $BASH_ENV
       - newman/newman-run:
           collection: .circleci/postman/postman_test.json
           timeout: '1000'
   jestmochak6:
     docker:
       - image: circleci/node:10.15.3
       - image: circleci/mongo:4.0.9
       - image: loadimpact/k6
     environment:
       - MONGO_URL: "mongodb://localhost:27017/herodb"
 #    working_directory: ~/
     steps:
       - run: npm update
       - checkout
       - restore_cache:
           keys:
             - cache-{{ checksum "package.json" }}
       - run: npm install
       - save_cache:
           paths:
             - ~/project/node_modules
           key: cache-{{ checksum "package.json" }}
       - run: npm run seed-db
       - run:
           command: npm run express-server
           background: true
       - run: sleep 2s
       - run: ps aux
       - run: npm run jest
       - run: npm run mocha
       - run: docker run -i loadimpact/k6 run - <.circleci/k6/main.js
 workflows:
   version: 2.1
   postman_and_main:
     jobs:
#      - postman
      - jestmochak6